### PR TITLE
Fix CLs method as it is supposed to be

### PR DESCRIPTION
**Pull request by tmombaecher**
Finally the CLs method is working as it is supposed to be (tested for the one-sided test statistic in the datasets case)
still to be done before the merge:
~1) implement properly into combiner case as well~
~2) make test statistics configurable~
~3) properly implement the `--pr` option for the datasets case to have the F&C method ready~

Still want to include the style comments made in analysis review:
- start plotting observed curve from measured value for one-sided test statistic
- fix expected curves at (POI=0,CLs=1)
- add dashed line for the best POI measurement

### CODE REVIEW

**Comment by matthewkenzie** [comment]
Great to see these developments being added. I ran the tutorial_datasets for these latest fixes and get the plots below. I looks like there is something not quite right going on with the Feldman-Cousins ("plugin"). The expected bands and observation look good (and I think as expected) but the normal plugin method should approximately follow the prob (regardless of any sort of CLs methodology).

Looking at these plots though it seems that the so-called "Mixed-CLs" sets a stronger limit than just the "Prob" method i.e. profile likelihood ratio? Is that really what we expect? I'm a bit surprised by that.

tutorial_dataset_branchingRatio_plugin
tutorial_dataset_branchingRatio_plugin_cls
tutorial_dataset_branchingRatio_plugin_cls_expected

**Comment by tmombaecher** [comment]
That's because the one-sided test statistic is used with the `-a plugin` method (currently hard coded), while with the prob method the two-sided test statistic is used.
I've started on making this configurable

**Comment by matthewkenzie** [comment]
Ah yes this makes sense. I think indeed that should be configurable as well so that it can be kept consistent between methods as much as possible. It should be structured (presumably it will be) such that you don't have to regenerate any toys just re-analyse them. Let me know once you are done and I can re-do my tests. Thanks again.

**Comment by tmombaecher** [comment]
yes, as it's just a redefinition of the test using the same likelihoods, this is done exactly that way.

**Comment by tmombaecher** [comment]
Ready for the tests

**Comment by matthewkenzie** [comment]
Thanks. Do I need to re-run the toys I made yesterday?

**Comment by matthewkenzie** [comment]
I tried some tests without regenerating, so ran on toys that had already been generated for the datasets tutorial example.

This is what I get:

 * The normal fitting routine. Uses two-sided test-stat by default. Looks good!
`-a plugin` 

tutorial_dataset_two-sided-fit

 * Adds in the basic CLs calculation (basically takes the previous fit and divides by CLb). Uses as default the two-sided test-stat. Looks good!
`-a plugin --cls 1`

tutorial_dataset_two-sided-fit-wcls

 * This is probably what one would call **the** CLs calculation. This I think is also fine? This ends up providing a stronger observed limit than the example above.  It certainly produces the expected / observed CLs band / plot as we want it to (I notice there is no smoothing applied here)?
`-a plugin --cls 2`

tutorial_dataset_two-sided-wcls2
tutorial_dataset_two-sided-wcls2_expected

* Normal routine but asking for the 1-sided test stat. Notice here that the Prob method still uses the 2-sided conversion. I think we could consider changing this to a 1-sided p-value interpretation for consistency?
`-a plugin --teststat 1`

tutorial_dataset_one-sided

 * Basic CLs but asking for the 1-sided test stat. As above. Could consider modifying the Prob calculation for a 1-sided conversion?
`-a plugin --teststat 1 --cls 1`

tutorial_dataset_one-sided-wcls

 * The advanced CLs asking for the 1-sided test stat. This I think the behaviour that the majority of users would actually want so we should make sure it's well advertised in this way. This CLs band plot with the one-sided test-stat is the one to use. I notice no smoothing also.
`-a plugin --teststat 1 --cls 2`

tutorial_dataset_one-sided-wcls2

tutorial_dataset_one-sided-wcls2_expected

 * A few points / possible additions (I can probably add these next week if you agree)
   * Add some printout to tell / remind the user what test stat is being used
   * What happened about CLs band smoothing?
   * I think when user ask for test-stat 1 the Prob method bands should also be changed to reflect a 1-sided conversion
   * There is some verbose printout at the moment which should be removed (I get several lines like "998.00	796.00	0.80")
   * There is an error printed by TLinearFitter (I think when trying to interpolate between points for the solution / interval)?

**Comment by tmombaecher** [comment]
With rerunning the toys you should also get the Feldman Cousins dealing properly. Haven't tried it yet.
- I see that apparently the proper CLs values from the prob method (and one-sided CLs+b) do not properly get picked up when drawing them together with the plugin methods.
I will try to check that next week
- the smoothing I moved to a kernel smoother with width 2*binwidth because the supersmoother was smoothing too strong and thus biased the expected curves.
- the other points you mentioned I will leave up to you, thanks for volunteering

**Comment by tmombaecher** [comment]
Ok,  I fixed
- that the prob plots are drawn properly 
- removed the debug messages
- added an information on the usage of the test stat
- used a mixed smoothing that worked for my analysis. But it's probably not useful for general purposes
- added a dashed line for the observed POI value in the CLs plot

So what is left to be done:
- make the dashed line optional with the command --ps -> this I will do tomorrow morning and then hand to you
- adapt the F&C approach to deal with boundaries also for the actually measured result -> the measurement should be modified, if the observed POI is outside the physical range

BTW: The F&C method works nicely, as this quick plot shows:
[tutorial_dataset_branchingRatio_plugin.pdf](https://github.com/gammacombo/gammacombo/files/4054835/tutorial_dataset_branchingRatio_plugin.pdf)

**Comment by matthewkenzie** [comment]
This is great! I don’t quite the last point though about the F&C approach to deal with boundaries for the actual measured result.

On 13 Jan 2020, at 17:28, Titus <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I fixed

  *   that the prob plots are drawn properly
  *   removed the debug messages
  *   added an information on the usage of the test stat
  *   used a mixed smoothing that worked for my analysis. But it's probably not useful for general purposes
  *   added a dashed line for the observed POI value in the CLs plot

So what is left to be done:

  *   make the dashed line optional with the command --ps -> this I will do tomorrow morning and then hand to you
  *   adapt the F&C approach to deal with boundaries also for the actually measured result -> the measurement should be modified, if the observed POI is outside the physical range

BTW: The F&C method works nicely, as this quick plot shows:
tutorial_dataset_branchingRatio_plugin.pdf<https://github.com/gammacombo/gammacombo/files/4054835/tutorial_dataset_branchingRatio_plugin.pdf>

**Comment by tmombaecher** [comment]
Ok, it's done.
What I mean with the F&C approach:
Consider the case that the best fit/global minimum is outside the physical range (e.g. measured branching fraction<0). Now we want to impose the physical ranges, i.e. request the F&C approach. For all fits of toys, where the minimum is outside the range we require a refit at the physical boundary. However, the observed global minimum (`chi2minGlobal`) is not obtained using this approach. We therefore run into an inconsistency that can easily screw the confidence intervals in these cases.
This I fixed by requiring the same procedure as in the toys.
Does that clarify?

**Comment by matthewkenzie** [comment]
Yes I think that makes sense. Looks good. I’ll run some more tests later today and then we can merge?

On 14 Jan 2020, at 10:25, Titus <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, it's done.
What I mean with the F&C approach:
Consider the case that the best fit/global minimum is outside the physical range (e.g. measured branching fraction<0). Now we want to impose the physical ranges, i.e. request the F&C approach. For all fits of toys, where the minimum is outside the range we require a refit at the physical boundary. However, the observed global minimum (chi2minGlobal) is not obtained using this approach. We therefore run into an inconsistency that can easily screw the confidence intervals in these cases.
This I fixed by requiring the same procedure as in the toys.
Does that clarify?

**Comment by tmombaecher** [comment]
Yes, I think so.
I did not fix the TLinearFitter error, though.

**Comment by matthewkenzie** [comment]
Looking great. A couple of minor things spotted when running tests on the datasets tutorial. I think these should be resolved before merge because it then covers all cases of anything someone would want to do and is consistent across methods. 
@tmombaecher I can have a look at sorting these if you want but as you've been doing most of the development on this recently it will probably be quicker if you can do it?

To make life easier I put the output of my plugin toys for the datasets tutorial here:
``/afs/cern.ch/user/m/mkenzie/public/forTitus/scan1dDatasetsPlugin_PDF_Dataset_branchingRatio`` so you shouldn't have to regenerate.

**Test Results:**

``--teststat 2 --cls 2``
tutorial_dataset_ts2_cls2
tutorial_dataset_ts2_cls2_expected

 * I'm not sure what's happening here with the Prob CLs - but shouldn't it in this case just be the likelihood ratio between the scan point and the point at 0 (i.e. just CLs+b/CLb)? This would then mean that it would align properly with what is called "Plugin CLs" in this plot.
 * I think we should think of a new name for "Mixed CLs" perhaps "Normal CLs" or "Default CLs"? 
 * Notice in the expected plot that the observed CLs points with values of 1 are not plotted 

``--teststat 1 --cls 2``

tutorial_dataset_ts1_cls2
tutorial_dataset_ts1_cls2_expected

 * In this case there is a problem with the Prob because it still plots the best fit point (so that should be removed). All the points below that best fit point in this case I guess will be 1. I think it's this problem which is messing up the Prob CLs here as well but not sure?
 * Then there is the same issue as above that the Plugin CLs is so different from the Prob CLs
 * Also the same issue as above in the expected plot with the observed values not being plotted if they are 1.
 * Again we should change the name for "Mixed CLs"

``--teststat 2 --cls 1``

tutorial_dataset_ts2_cls1

 * This will be fine once the issues above are fixed (however there are two legend entries for Plugin CLs)

``--teststat 1 --cls 1``
tutorial_dataset_ts1_cls1

 * This will be also fixed when items above are fixed

**Comment by tmombaecher** [comment]
A bit later than wished, I have put in the last tiny changes (again, the TLinearFitter errors need some more thought, but they don't seem to affect the interval computation)
1. I renamed "Mixed CLs" to "Standard CLs" and "Plugin CLs" to "Simplified CLs"
- The Standard CLs and the Prob CLs should be rather close (apart from asymptotic assumptions and boundary behaviour, which most often does not make any difference)
- the "Simplified CLs", checking `chi2minToy-chi2minGlobalToy>chi2minBkg-chi2minGlobal`, is based on my wrong understanding 2 years ago and is simply wrong and I am not sure, whether the description `CLb=CLs+b(s=0)` is accurate in this implementation. So I simply put "deprecated" in the description.
2. The kink in the one-sided Prob CLs distribution and the discontinuity in the Standard CLs have the same origin: the definition change at `mu=muhat`. For the Prob CLs the CLs+b values are fixed to 0.5, for the Standard CLs they are 1 (because I want to finish this today, I just link the LHCb internal document [AnaNote_with_RooStats](https://twiki.cern.ch/twiki/pub/LHCbPhysics/Bs2stKmutau/LHCb-ANA-2018-040_v1.5.pdf)). So this behaviour is consistent between GammaCombo and RooStats.
3. During my analysis the reviewers suggested to remove the points with `mu<muhat` for the observed curve for the one-sided test stat, as the test stat is defined to be 0 for those points. So this choice is deliberate (and we found it sensible, though debatable). I removed this for the two-sided teststat
4. The plotting of the measured value in the p-value plots for the one-sided test stat is now gone
5. The duplicates in the legend (coming from multiply writing the cls plots when giving the same argument many times) are also gone
tutorial_dataset_branchingRatio_plugin_cls_expected
tutorial_dataset_branchingRatio_plugin_cls

**Comment by tmombaecher** [comment]
Will merge tomorrow, if nobody objects.

**Comment by matthewkenzie** [comment]
Yes that would be perfect. I suggest once done we also then do a merge with the master and release a new version.

**Pull request merged**
