### PR TITLE
Remove duplicate code in Constructors of scan classes

### PR DESCRIPTION
**Pull request by KonstantinSchubert**
I will also extend the travis checks a bit.

### CODE REVIEW

**Comment by KonstantinSchubert** [comment]
The CI test is failing now becuase there is a segfault when running the tutorial. 
The segfault is strange and it doesn't occur on my system (Arch Linux), only in the test container.
I am trying to get behind it.

**Comment by matthewkenzie** [comment]
Oh dear. Let me know if you need me to test something on OSX.

**Comment by KonstantinSchubert** [comment]
With root6 there is no issue. I will check if  a newer version of root5 resolves it as well.

**Comment by KonstantinSchubert** [comment]
I think this can be merged now.

**Pull request merged**
