### PR TITLE
Make PDF_Datasets_Abs non-abstract and rename it to PDF_Datasets

### LINKED ISSUE #61: Make PDF_Datasets_Abs a self-sustained default that does not need to be implemented
In the current iteration we require users to write a pdf class that inherits from PDF_Datasets_Abs.
After discussion with Max we agreed that it makes sense to provide a sensible and functioning default implementation of this class. 

Users that need to tinker with the fit procedure can extend it via inheritance.

### PR DESCRIPTION
**Pull request by KonstantinSchubert**
This should also resolve #61 .

### CODE REVIEW

**Comment by KonstantinSchubert** [comment]
Please don't merge yet, I still want to properly implement the seed shift in the default implementations of the toy generators.

**Comment by mschlupp** [comment]
You can have a look at the B2mm package.
The `void PDF_B_MuMu::generateToys(int SeedShift)` function implements it in a somewhat trivial way. This is, however, not tested, because it was never used.

**Comment by KonstantinSchubert** [comment]
It should be implemented now. I created a new function because the seed-setting is needed both for the `generateToys` and for the `generateToysGlobalObservables` function. 
Both of these will receive the same seed if they are called with the same seedshift. Since they are generating different variables this shouldn't be a problem.

**Comment by KonstantinSchubert** [comment]
The RooRandom documentation says that TRandom3 is used by default:
https://root.cern.ch/doc/v606/classRooRandom.html#ab03d1bab07599fabcd4b30e48a2951ca

TRandom3's seed setter does not seem to suffer from the 100ns - issue that TRandom1 does. Compare the documentation here: 
https://root.cern.ch/doc/v606/classTRandom3.html#ac9e3ef3550f8eb4ecd6f676543ef2e90
and here:
https://root.cern.ch/doc/master/classTRandom1.html#ad5cde83ce5577030b531180af22d19d5

Only for TRandom1, the 100ns issue is mentioned.

I have updated the comments to reflect this.

**Comment by mschlupp** [comment]
Is that true for ROOT versions from 5.34/24+?

In any case, even 100ns is sufficient for most use cases.

**Comment by mschlupp** [comment]
Please check:
in the DatasetsTutorial: 
# A)
```C++
 +  // PDF_Datasets* pdf = new PDF_Datasets(workspace);
 +  PDF_Datasets* pdf = new PDF_DatasetTutorial(workspace);
```
Why not using the first line? This would illustrate that now extra classes are necessary for standard and easy use cases.

# B)
You deleted the option to perform the simple prob scan with the Datasets scanner. Please keep this possibility. I commented on the specific commit.

**Comment by KonstantinSchubert** [comment]
Regarding A) - sorry, that's a mistake. It is a relict of my testing.

**Comment by KonstantinSchubert** [comment]
Regarding B) :
You mean I should put the `doProbScanOnly` switch back in? Sorry for
removing this, no idea why I did it.
When we put this back in we must also make sure that the GammaComboEngine
calls the `scanner->performProbScanOnly(true)` method when the `-a prob`
argument is passed, right?

I think I was a bit confused because the whole class is called
MethodDatasetsPLUGINScan. So if I am seeing this right it does both the
PLUGIN and the PROB scan for datasets?

**Comment by mschlupp** [comment]
#### Switch: 
I think gcEngine does not need to call `scanner->performProbScanOnly(true)` 
The datasets scanner gets the arg parser, right? So we can simply let the scanner decide which scan to do, by e.g. 
```
if(args->isAction('prob'))
   this->performProbScanOnly(true)
```
I prefer this over gcEngine setting the switch.

#### Naming
That is a good point. We could rename the scanner as well. 
`MethodDatasetsScan` is shorter and not confusing in terms of which statistical method is used.

**Comment by KonstantinSchubert** [comment]
I think I got it fixed but the fix isn't very pretty.

**Pull request merged**
