### PR TITLE
Datasets dev

### PR DESCRIPTION
**Pull request by mschlupp**
Integrate updated (yet named Generic) classes along with necessary changes to run the full package with up-to-date core classes. 

Full plugin scans do not yet work properly.

### CODE REVIEW

**Comment by matthewkenzie** [comment]
I would rather that the cmake/combiners.cmake was left by default with only the "tutorial" part not commented. This means that people getting the package do not need any of the private sub packages. Could you not overwrite that file in your commit please?

**Comment by mschlupp** [comment]
makes sense. done

**Comment by KonstantinSchubert** [comment]
I suggest we do not merge this pull request before the other one regarding travis is merged.

This way we can fast-forward the development branch to also include the travis commit without including the changes that are coming with this Pull Request.

**Comment by matthewkenzie** [comment]
Agreed. Travis merge done. Will now merge this one.

**Pull request merged**
