### PR TITLE
Datasets dev

### PR DESCRIPTION
**Pull request by KonstantinSchubert**
I managed to get the tutorial to run without segfaults (nothing more so far.
During this process, I made a few changes to the PDF_Datasets_Abs and thereby also solved issue #40.

### CODE REVIEW

**Comment by KonstantinSchubert** [comment]
Also, issue #37 has been resolved.

**Comment by matthewkenzie** [comment]
CI check failed. Any ideas why?

**Comment by KonstantinSchubert** [comment]
Looking at the "details", it looks like Travis timed out while pulling the
docker image.

Therefore I would say it's a problem of my ci setup. I'm sorry for that.
The code itself should be compiling.

**Comment by KonstantinSchubert** [comment]
I re-ran the build and it passed.

**Pull request merged**
