### PR TITLE
Datasets: use bkg if bkg pdf set, proper hChi2min2dplotting, debug plots

### LINKED ISSUE #66: Command line option for non-linear interpolations
What is the opinion about a command line option that enables non-linear interpolation, especially in the OMCL plot? I think, in the OMCL plot, the same interpolation should be plotted that was used to calculate the confidence levels. Therefore, the interpolation method used to calculate the confidence levels should be known to the respective scanner class as well as the OMCL plot class. We could use the already implemented---I suspect linear---interpolation as default and add the possibility for e.g. cubic splines.

### LINKED ISSUE #122: Fitting procedures and chi2 histograms
This is a compatibility problem between the datasets and the combination part:

In the combination part, the fitting is done via `RooFitResult* Utils::fitToMin(RooAbsPdf *pdf, bool thorough, int printLevel)` (in https://github.com/gammacombo/gammacombo/blob/master/core/src/Utils.cpp), where AFAIK the fitting metric is changed to `-2log(likelihood)` and also somehow the global minimum of the fit is set to zero. 

In the datasets part, the fitting is done via the usual `RooAbsPdf->fitTo(RooDataset)` method, which uses the minimum negative loglikelihood as metric and does not correct wrt global minimum. In the scan2d case this minimum `chi2=2*MinNLL(fitresult)` from the fit is handed to the `hchi2min2d` histogram, which is drawn by the `OneMinusCLPlot2d::DrawFull()` method as a deltachi2. Thus it's wrong, because the global minimum doesn't get subtracted in this case.

We should adapt the fitting for the datasets part. But let's make sure to keep the fitting configurable (overridable) for the user.

### PR DESCRIPTION
**Pull request by tmombaecher**
A few fixes for the datasets part:
* If a bkg pdf is set use bkg pdf for CLs method (before: define bkg pdf as best fit with `scanVar=0`, this is still the backup solution if no bkg pdf is set)
* Closes #122: Redefine hChi2min2d as `chi2minScan - chi2minGlobal`. This is then similar to what happens in the combiner part of GammaCombo, where the normalisation to the likelihood minimum is done already in the `Utils::fitToMin` etc. methods
* Closes #66: Actually activate the quadratic interpolation for the calculation of the interval boundary, which was not used due to a bug before.

### CODE REVIEW

**Comment by matthewkenzie** [comment]
I see already we have a case where something changes and the (rather) strict CI requirements fail. In this case the Nbkg is not the same as expected (I guess because the definition of the background pdf has now changed)?

One solution is to modify `scripts/run_ci_tests.py` such that this will now pass

**Comment by tmombaecher** [comment]
Yes, I will clean up once I have included all intended changes. I am actually not sure why this crashes. It shouldn't. I'll have to look into the logs/reproduce.

**Comment by matthewkenzie** [comment]
The issue can be seen here:

https://github.com/gammacombo/gammacombo/pull/207/checks#step:6:17

The output .dat file (`plots/par/tutorial_dataset_PDF_Dataset_branchingRatio.dat`) is expected to have the following result for the `Nbkg` line:

```bash
Nbkg                4990.208984   -71.760254    71.760254
```

**Comment by tmombaecher** [comment]
It seems there can be numerical effects (e.g. from starting value differences). I see now
```
Nbkg                       4990.208984   -71.760193    71.760193
```
Which is the same but not exactly as what you found.

**Comment by tmombaecher** [comment]
Nice! with a little looser requirement on the numerical result, the check is now passed. Nevertheless want to check all new debug plots before merging

**Comment by matthewkenzie** [comment]
Very nice. In fact I think that slightly looser requirements are indeed desirable because of little numerical differences like this. Great work!

**Comment by tmombaecher** [comment]
With these changes I consider the pull request complete now. Will merge tomorrow morning.

**Comment by matthewkenzie** [comment]
This is all looking very nice and good that we are managing to close a few issues and that someone has had a good look at the control plots which haven't been looked over for a while.

One little thing I noticed is that `MethodDatasetsPluginScan.cpp` has a `drawPlots` member but this seems fairly defunct as we can just use `arg->controlplots`?

**Comment by tmombaecher** [comment]
Yes, thanks for the pointer. 
- I will remove that member. We also do not use it in the combiner case, so better to have a uniform treatment.
- the goodness-of-fit control plot needs a fix still. Turns out the only thing one can probably learn from that is whether the likelihood is properly smooth close to the best fit point. It's not clear to me whether it could be removed then, but keeping it for now.
- Another thing I noticed is that the combiner control plots crash when there's no solution found (as in the `bin/tutorial -c 1 --var a_gaus -a plugin --controlplots`). Haven't found the source yet, but will try to fix out as well.

Try to have a look this afternoon.

**Comment by matthewkenzie** [comment]
Interesting about this crash. Perhaps we should add `--controlplots` as part of the CI tests?

**Comment by tmombaecher** [comment]
> Interesting about this crash. Perhaps we should add `--controlplots` as part of the CI tests?

added to the `-a plugin` checks. The control plots should at least not crash. However, one might think about some more generalisation. We probably want the same control plots for both cases. But currently they are both tailored for the datasets/combiner use case. So the layout might change at some point.

The crash actually happened because of a bad covariance quality of the tutorial combiner. This happens because it tries to fit both parameters, `a_gaus` and `b_gaus`, though only `a_gaus` is constrained with some model. Don't know whether that's an error in the tutorial or a more general problem?
Anyhow, as for the control plots, the error is caught with an appropriate message. You cannot do control plots, if your Prob free fit is broken.

All the other points are fixed as well.

**Comment by tmombaecher** [comment]
Ok, ready to merged then

**Comment by matthewkenzie** [comment]
> The crash actually happened because of a bad covariance quality of the tutorial combiner. This happens because it tries to fit both parameters, `a_gaus` and `b_gaus`, though only `a_gaus` is constrained with some model. Don't know whether that's an error in the tutorial or a more general problem?

Mmmm. Might need to look into that a little bit but for now let's go ahead and merge

**Comment by tmombaecher** [comment]
> > The crash actually happened because of a bad covariance quality of the tutorial combiner. This happens because it tries to fit both parameters, `a_gaus` and `b_gaus`, though only `a_gaus` is constrained with some model. Don't know whether that's an error in the tutorial or a more general problem?
> 
> Mmmm. Might need to look into that a little bit but for now let's go ahead and merge

Forgot to say that I fixed the error: The PDF_Gaus was having two parameters: `a_gaus` and `b_gaus`, but a model that constrains only one: `a_gaus`. So I removed the `b_gaus` (for which we have a different pdf in the tutorial, actually)

**Comment by matthewkenzie** [comment]
> Forgot to say that I fixed the error: The PDF_Gaus was having two parameters: `a_gaus` and `b_gaus`, but a model that constrains only one: `a_gaus`. So I removed the `b_gaus` (for which we have a different pdf in the tutorial, actually)

Yes this makes sense (not sure why that was there). Once the CI runs I'm happy for you to merge this (and have the satisfaction of closing the relevant issues).

Thanks @tmombaecher. Great work!

**Pull request merged**
