### PR TITLE
Inefficiencies check

### PR DESCRIPTION
**Pull request by tmombaecher**
Remove inefficiencies/bugs reported in #224.

### CODE REVIEW

**Comment by tmombaecher** [comment]
1. This MR now implements a change of fit strategies if a fit fails.
2. Fits are only repeated if necessary. This removes ~25% of previously performed fits (i.e. 25% speedup!) and is now optimal for the default case (no physical range, stable fits).
3. A fit that fails is determined as fit status!=0 and covQual!=3 in the PDF_Datasets class like e.g. in https://github.com/gammacombo/gammacombo/blob/f6ebeca4633b8bd1ca45c5d50a79f8541e6b0787/core/src/PDF_Datasets.cpp#L310.
This requirement we also impose when classifying toys as good/bad. When testing in one case, I did not see a significantly increased amount of toy fits, yet a few percent gain in the fraction of good toys. If the fit fails, the status is printed to warn the user. If the user doesn't want the behaviour, he/she can override the `PDF_Datasets` class anyway.
@fionnbishop, this what you had in mind, right?
From my POV this is ready to merge. There's no crucial behaviour changes involved, so I would merge by tomorrow night, if nobody objects.

**Comment by fionnbishop** [comment]
@tmombaecher Yes, this looks helpful, thanks for adding. However, I believe this doesn't take into account the EDM as that is included in the fit status later:
https://github.com/gammacombo/gammacombo/blob/f6ebeca4633b8bd1ca45c5d50a79f8541e6b0787/core/src/MethodDatasetsPluginScan.cpp#L1247-L1252
Is there any reason not to move this inside ::fit and ::fitBkg?

**Comment by tmombaecher** [comment]
> @tmombaecher Yes, this looks helpful, thanks for adding. However, I believe this doesn't take into account the EDM as that is included in the fit status later:
> 
> https://github.com/gammacombo/gammacombo/blob/f6ebeca4633b8bd1ca45c5d50a79f8541e6b0787/core/src/MethodDatasetsPluginScan.cpp#L1247-L1252
> 
> Is there any reason not to move this inside ::fit and ::fitBkg?

The EDM criterion is included in `RooFitResult::status()`(see https://root.cern.ch/root/htmldoc/ROOT__Minuit2__Minuit2Minimizer.html#ROOT__Minuit2__Minuit2Minimizer:Minimize)
These lines are an attempt to propagate different reasons for failing into the toy tree (probably imperfect) and not to refit at this point anymore. 
So we don't need this redundant check in the `fit()` and `fitBkg()` functions, I believe.

**Comment by fionnbishop** [comment]
Is the EDM criterion in RooFitResult::status() not much higher than the 1.e-3 used in GammaCombo?
(I have been unsuccessful in trying to find the exact EDM used by RooFit, but I don't recall often if ever seeing that error code, whereas it is not difficult to hit 1e-3)

**Comment by tmombaecher** [comment]
It's written e.g. here: https://cds.cern.ch/record/2296388/files/minuit.pdf

**Comment by fionnbishop** [comment]
OK yes, you're right. I thought I had experienced it returning an OK fit status with a too-high EDM, but having looked carefully at a suitable example, it does show the correct behaviour, so not sure why I thought that!

**Pull request merged**
