### PR TITLE
Allow setting/removing physical range in datasets

### PR DESCRIPTION
**Pull request by matthewkenzie**

### CODE REVIEW

**Comment by tmombaecher** [comment]
I have two questions here:
1) why do you merge from your master into the gammacombo:master? Is the gammacombo:master actually up-to-date? Shouldn't it be merged into development and then released into master?
2) what does the "adjustRanges" and "fixParameters" actually do? If I read this correctly, it changes the allowed parameter ranges. If this is done for the fit, it will bias the fit (which we certainly not want). If this is not applied for the fit, I don't see the impact it can have.

**Comment by matthewkenzie** [comment]
1. The master is up to date with development (since we did so for the last release). I can of course change this. Also because of the small bug fix I wanted to get it into master quickly.
2. Fix parameter will just fix that parameter in the scan. adjustRanges will change the allowed range of the given parameter(s). If you run with no --pr option as you did before then nothing will change. If you want to enforce a physical boundary for say the branchingRatio then you could do: --pr and --prange branchingRatio=0.:2.5e-6. I think that for CLs the recommendation is often not to enforce such a boundary (and in fact in the branchingRatio case I don’t think you would want to). I thought the point was you wanted the option to enforce a boundary (which can now be done) and thus produce the FC example at a boundary for the datasets. This clearly will “bias" your fit depending on how you define bias - the best fit value won’t change (unless e.g. for the branching ratio it was previously <0, it will now be 0) but of course the confidence interval from FC method near the boundary will give a more accurate result (i.e. one that has better coverage). 

I think for your analysis then nothing needs to change from what was done before (apart from your various fixes to CLs). This stuff now gives the user the option to enforce a physical range if they want to.

**Comment by tmombaecher** [comment]
1) yes, please let's go the orthodox way and move through the development branch, which makes also the forking more consistent
2) I was thinking of another way to implement the adjustRanges function, let me clarify and see whether what I mean is actually what you implemented:
- what should be done in the FeldmanCousins approach and therefore included in the `--pr` option is that if the fit finds a minimum outside the physical range, the fit should be redone with the POI set to the closest value still inside the physical range (needs a refit, as it also might affect nuisance parameters)
- what should not be done is that the range for the free fit is shrinked. Because RooFit (or Minuit) will apply some Likelihood modifications at parameter boundaries that are to move the fit away from them. But this Fit bias we don't want. Or is that a negligible effect? I don't have a feeling for this. It's certainly not "correct".

**Comment by matthewkenzie** [comment]
1. Ok.
2. Yes I see your point. That is not how I have written it and indeed the way I have done it will end up affecting the likelihood ratio definition if that range is forced. We should implement it the way you suggest. Unclear what should be done about the Prob method with --pr though (i.e do we leave it like this or just leave it so that it is no different from prob when no range is asked for)

**Comment by matthewkenzie** [comment]
We decided to close this without merging.

**Pull request closed without merging**
