### PR TITLE
Link RooFitMore to support classes like RooHypatia2

### PR DESCRIPTION
**Pull request by tmombaecher**
RooHypatia2 is quite a useful function, but lives in a different ROOT directory (RooFitMore). 
To support its use we need to add the linking to the RooFitMore directory.

### CODE REVIEW

**Comment by tmombaecher** [comment]
ok, the build fails as the `RooFitMore` directory only exists for ROOT versions >6/20

**Comment by matthewkenzie** [comment]
Ok so need to require a newer version in the CMake and for the CI?

**Comment by tmombaecher** [comment]
yes, I was still searching for the docker image actually to check what all this entails (to judge whether we actually want to do this now, it's not backward compatible)

**Comment by tmombaecher** [comment]
another possibility is to make some exception in case the lib is unavailable and thus keep some backward compatibility. Need to find out how this goes.

**Comment by tmombaecher** [comment]
I added an exception and a message for both cases (whether RooFitMore has been included or not). Maybe that serves as sufficient test that things work?

**Pull request merged**
